name: Desktop app (Python) continuous integration

on:
  push:
    branches: [master, desktop_client_dev]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
        architecture: 'x64'
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat env update --file desktop_client\desktop\desktop\Installation\environment.yml --name base
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Lint the main directory with flake8
      run: |
        cd desktop_client\desktop\desktop
        # Activate the base environment
        C:\Miniconda\condabin\conda.bat activate base
        C:\Miniconda\condabin\conda.bat install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint the test directory with flake8
      run: |
        cd desktop_client\desktop\desktop\tests
        # Activate the base environment
        C:\Miniconda\condabin\conda.bat activate base
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics